include $(CLEAR_VARS)
LOCAL_MODULE := Remote
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := IR_Remote/LetvRemoteControl.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Remote_work
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := IR_Remote/UEIQuicksetSDKLeTV.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
